/**
 * The Transaction Purposes as they were originally written — **seed data now,
 * not a runtime source.**
 *
 * A Purpose is exactly one Budget Category x one Partner Category x one
 * direction, which is what lets it resolve to a single account. It used to live
 * here as 22 constants. It lives in `sys_purpose` now, because the Budget
 * Categories it classifies became rows: a category created through the GUI that
 * no Purpose named could be planned, mapped and given a subject book, and still
 * never reach a Cash Bank Transaction. That was the last link that needed a
 * developer, and it is the reason this moved.
 *
 * The 22 below are kept **verbatim** and planted once by `prisma/seed.ts`,
 * because two things about them cannot be regenerated:
 *
 *   - their **keys**. `fin_cash_bank_transaction.purpose` already holds
 *     `TTP_CAB_IN` on posted documents, and a posted document is permanent.
 *   - their **labels**. "Penerimaan Pinjaman dari Cabang" is a Hutang receipt
 *     and "Pemberian Advance kepada Karyawan" is a Piutang payment: the sentence
 *     names the business event, not the classification, and no template
 *     produces either. 21 of the 22 fit a pattern; that one does not.
 *
 * Everything after the seed is generated by `syncPurposes` in `purposes.ts` and
 * read through it. **Do not add an entry here** — a new Purpose comes from a new
 * Budget Category or a new Partner Category pairing, which is the whole point.
 */
import type { Direction } from "./classification";

export type { Direction };

export type Purpose = {
  key: string;
  label: string;
  direction: Direction;
  /** The Budget Category's label. Display only — logic keys on its id. */
  budgetCategory: string;
  /** null = this purpose takes no partner. */
  partnerCategory: string | null;
};

/**
 * The historical set, planted once. Renamed from `PURPOSES` so that nothing
 * reads it by accident expecting the live catalogue.
 */
export const SEED_PURPOSES: Purpose[] = [
  { key: "TTP_CAB_IN",  label: "Penerimaan Titipan dari Cabang",               direction: "In",  budgetCategory: "Titipan",         partnerCategory: "Cabang" },
  { key: "TTP_CAB_OUT", label: "Pengembalian Titipan ke Cabang",               direction: "Out", budgetCategory: "Titipan",         partnerCategory: "Cabang" },
  { key: "TTP_SH_IN",   label: "Penerimaan Titipan dari Stakeholder",          direction: "In",  budgetCategory: "Titipan",         partnerCategory: "Stakeholder" },
  { key: "TTP_SH_OUT",  label: "Pengembalian Titipan ke Stakeholder",          direction: "Out", budgetCategory: "Titipan",         partnerCategory: "Stakeholder" },
  { key: "HTG_CAB_IN",  label: "Penerimaan Pinjaman dari Cabang",              direction: "In",  budgetCategory: "Hutang",          partnerCategory: "Cabang" },
  { key: "HTG_CAB_OUT", label: "Pembayaran Hutang ke Cabang",                  direction: "Out", budgetCategory: "Hutang",          partnerCategory: "Cabang" },
  { key: "HTG_KRY_IN",  label: "Penerimaan Pinjaman dari Karyawan",            direction: "In",  budgetCategory: "Hutang",          partnerCategory: "Karyawan" },
  { key: "HTG_KRY_OUT", label: "Pembayaran Hutang ke Karyawan",                direction: "Out", budgetCategory: "Hutang",          partnerCategory: "Karyawan" },
  { key: "HTG_SH_IN",   label: "Penerimaan Pinjaman dari Stakeholder",         direction: "In",  budgetCategory: "Hutang",          partnerCategory: "Stakeholder" },
  { key: "HTG_SH_OUT",  label: "Pembayaran Hutang ke Stakeholder",             direction: "Out", budgetCategory: "Hutang",          partnerCategory: "Stakeholder" },
  { key: "PTG_CAB_OUT", label: "Pemberian Pinjaman kepada Cabang",             direction: "Out", budgetCategory: "Piutang",         partnerCategory: "Cabang" },
  { key: "PTG_CAB_IN",  label: "Penerimaan Pelunasan Piutang dari Cabang",     direction: "In",  budgetCategory: "Piutang",         partnerCategory: "Cabang" },
  { key: "PTG_KRY_OUT", label: "Pemberian Advance kepada Karyawan",            direction: "Out", budgetCategory: "Piutang",         partnerCategory: "Karyawan" },
  { key: "PTG_KRY_IN",  label: "Penerimaan Pelunasan Piutang dari Karyawan",   direction: "In",  budgetCategory: "Piutang",         partnerCategory: "Karyawan" },
  { key: "PTG_SH_OUT",  label: "Pemberian Pinjaman kepada Stakeholder",        direction: "Out", budgetCategory: "Piutang",         partnerCategory: "Stakeholder" },
  { key: "PTG_SH_IN",   label: "Penerimaan Pelunasan Piutang dari Stakeholder", direction: "In", budgetCategory: "Piutang",         partnerCategory: "Stakeholder" },
  { key: "PRV_SH_OUT",  label: "Pembayaran Prive kepada Stakeholder",          direction: "Out", budgetCategory: "Prive",           partnerCategory: "Stakeholder" },
  { key: "PRV_SH_IN",   label: "Penerimaan Pengembalian Prive dari Stakeholder", direction: "In", budgetCategory: "Prive",          partnerCategory: "Stakeholder" },
  { key: "AST_OUT",     label: "Pembelian Aset",                               direction: "Out", budgetCategory: "Asset",           partnerCategory: null },
  { key: "BYA_OUT",     label: "Pembayaran Biaya",                             direction: "Out", budgetCategory: "Biaya",           partnerCategory: null },
  { key: "INV_CAB_OUT", label: "Pengeluaran Investasi kepada Cabang",          direction: "Out", budgetCategory: "Investasi",       partnerCategory: "Cabang" },
  { key: "HIN_CAB_IN",  label: "Penerimaan Hasil Investasi dari Cabang",       direction: "In",  budgetCategory: "Hasil Investasi", partnerCategory: "Cabang" },
];
